name: Release

on:
  push:
    tags: 
    - 'v*.*.*'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install fine-cross compiler
      run: go install github.com/fyne-io/fyne-cross@v1.1.3   
    - name: Install fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
    - name: Set version
      run: sed "s/Commit  = \"none\"/Commit  = \"$(git rev-parse --short HEAD)\"/g" internal/utils/version.go
    - name: Build
      run: fyne-cross linux -app-id org.fairdatasociety.fairpass -icon icon.png
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: fyne-cross/dist/linux-amd64/FairPass.tar.xz
